### ISSUE TITLE
Issues on zooming

### ISSUE THREAD

**Issue by romiras** [evanw/theta#1]
Hi,
I was just curious why I can see these issues on zooming:
![thetamath](https://cloud.githubusercontent.com/assets/298544/14376931/807f75a8-fd75-11e5-99f4-5f4c19f9e1ef.png)

**Comment by evanw** [comment]
You're seeing the limits of floating-point precision on your GPU. It's a fundamental limitation of my approach (compiling the equation to GLSL). GPUs prefer speed over accuracy so floating-point precision breaks down pretty quickly. The pattern will look different on different GPUs because it's implementation-dependent.

I considered trying to compile equations into code that emulates double-precision numbers using tuples of two single-precision numbers to avoid this limitation but that seemed hard.

**Comment by romiras** [comment]
Thanks for explanation.
